name: Publish GitHub Pages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Publish
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.PUBLISH_TOKEN }}
        deploy-branch: master
